# Form implementation generated from reading ui file 'AddStyleWindow.ui'
#
# Created by: PyQt6 UI code generator 6.0.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddStyleWindow(object):
    def setupUi(self, AddStyleWindow):
        AddStyleWindow.setObjectName("AddStyleWindow")
        AddStyleWindow.resize(609, 366)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        AddStyleWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(AddStyleWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bAddStyle = QtWidgets.QPushButton(self.centralwidget)
        self.bAddStyle.setGeometry(QtCore.QRect(500, 300, 91, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        self.bAddStyle.setFont(font)
        self.bAddStyle.setObjectName("bAddStyle")
        self.StyleTextLabel = QtWidgets.QLabel(self.centralwidget)
        self.StyleTextLabel.setGeometry(QtCore.QRect(10, 10, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        self.StyleTextLabel.setFont(font)
        self.StyleTextLabel.setObjectName("StyleTextLabel")
        self.ptStyleText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ptStyleText.setGeometry(QtCore.QRect(10, 40, 591, 251))
        self.ptStyleText.setObjectName("ptStyleText")
        self.SyleNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.SyleNameLabel.setGeometry(QtCore.QRect(10, 300, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        self.SyleNameLabel.setFont(font)
        self.SyleNameLabel.setObjectName("SyleNameLabel")
        self.StyleNameText = QtWidgets.QLineEdit(self.centralwidget)
        self.StyleNameText.setGeometry(QtCore.QRect(120, 300, 191, 22))
        self.StyleNameText.setObjectName("StyleNameText")
        AddStyleWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddStyleWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 609, 22))
        self.menubar.setObjectName("menubar")
        AddStyleWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddStyleWindow)
        self.statusbar.setObjectName("statusbar")
        AddStyleWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddStyleWindow)
        QtCore.QMetaObject.connectSlotsByName(AddStyleWindow)

    def retranslateUi(self, AddStyleWindow):
        _translate = QtCore.QCoreApplication.translate
        AddStyleWindow.setWindowTitle(_translate("AddStyleWindow", "Add Style"))
        self.bAddStyle.setText(_translate("AddStyleWindow", "Add Style"))
        self.bAddStyle.setShortcut(_translate("AddStyleWindow", "Return"))
        self.StyleTextLabel.setText(_translate("AddStyleWindow", "Style Text:"))
        self.SyleNameLabel.setText(_translate("AddStyleWindow", "Style Name:"))
