# Form implementation generated from reading ui file 'ChangeStyleWindow.ui'
#
# Created by: PyQt6 UI code generator 6.0.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChangeStyleWindow(object):
    def setupUi(self, ChangeStyleWindow):
        ChangeStyleWindow.setObjectName("ChangeStyleWindow")
        ChangeStyleWindow.resize(452, 107)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        ChangeStyleWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ChangeStyleWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bChangeStyle = QtWidgets.QPushButton(self.centralwidget)
        self.bChangeStyle.setGeometry(QtCore.QRect(160, 40, 111, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        self.bChangeStyle.setFont(font)
        self.bChangeStyle.setObjectName("bChangeStyle")
        self.StyleLabel = QtWidgets.QLabel(self.centralwidget)
        self.StyleLabel.setGeometry(QtCore.QRect(10, 10, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        self.StyleLabel.setFont(font)
        self.StyleLabel.setObjectName("StyleLabel")
        self.cbStyles = QtWidgets.QComboBox(self.centralwidget)
        self.cbStyles.setGeometry(QtCore.QRect(70, 10, 371, 22))
        self.cbStyles.setObjectName("cbStyles")
        ChangeStyleWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChangeStyleWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 22))
        self.menubar.setObjectName("menubar")
        ChangeStyleWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChangeStyleWindow)
        self.statusbar.setObjectName("statusbar")
        ChangeStyleWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChangeStyleWindow)
        QtCore.QMetaObject.connectSlotsByName(ChangeStyleWindow)

    def retranslateUi(self, ChangeStyleWindow):
        _translate = QtCore.QCoreApplication.translate
        ChangeStyleWindow.setWindowTitle(_translate("ChangeStyleWindow", "Change Style"))
        self.bChangeStyle.setText(_translate("ChangeStyleWindow", "Change Style"))
        self.bChangeStyle.setShortcut(_translate("ChangeStyleWindow", "Return"))
        self.StyleLabel.setText(_translate("ChangeStyleWindow", "Style:"))
