# Form implementation generated from reading ui file 'ClearAccInFolderWindow.ui'
#
# Created by: PyQt6 UI code generator 6.0.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClearAccInFolderWindow(object):
    def setupUi(self, ClearAccInFolderWindow):
        ClearAccInFolderWindow.setObjectName("ClearAccInFolderWindow")
        ClearAccInFolderWindow.resize(452, 107)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        ClearAccInFolderWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ClearAccInFolderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FolderNameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.FolderNameInput.setGeometry(QtCore.QRect(120, 10, 321, 22))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.FolderNameInput.setFont(font)
        self.FolderNameInput.setObjectName("FolderNameInput")
        self.bClearAccInFolder = QtWidgets.QPushButton(self.centralwidget)
        self.bClearAccInFolder.setGeometry(QtCore.QRect(150, 40, 131, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        self.bClearAccInFolder.setFont(font)
        self.bClearAccInFolder.setObjectName("bClearAccInFolder")
        self.FolderNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.FolderNameLabel.setGeometry(QtCore.QRect(10, 10, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        self.FolderNameLabel.setFont(font)
        self.FolderNameLabel.setObjectName("FolderNameLabel")
        ClearAccInFolderWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ClearAccInFolderWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 22))
        self.menubar.setObjectName("menubar")
        ClearAccInFolderWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ClearAccInFolderWindow)
        self.statusbar.setObjectName("statusbar")
        ClearAccInFolderWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ClearAccInFolderWindow)
        QtCore.QMetaObject.connectSlotsByName(ClearAccInFolderWindow)

    def retranslateUi(self, ClearAccInFolderWindow):
        _translate = QtCore.QCoreApplication.translate
        ClearAccInFolderWindow.setWindowTitle(_translate("ClearAccInFolderWindow", "Clear Acc In Folder"))
        self.bClearAccInFolder.setText(_translate("ClearAccInFolderWindow", "Clear Acc In Folder"))
        self.bClearAccInFolder.setShortcut(_translate("ClearAccInFolderWindow", "Return"))
        self.FolderNameLabel.setText(_translate("ClearAccInFolderWindow", "Folder Name:"))
