# Form implementation generated from reading ui file 'ConfirmationWindow.ui'
#
# Created by: PyQt6 UI code generator 6.0.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConfirmationWindow(object):
    def setupUi(self, ConfirmationWindow):
        ConfirmationWindow.setObjectName("ConfirmationWindow")
        ConfirmationWindow.resize(395, 108)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        ConfirmationWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(ConfirmationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.QuestionLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuestionLabel.setGeometry(QtCore.QRect(8, 0, 381, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.QuestionLabel.setFont(font)
        self.QuestionLabel.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.QuestionLabel.setObjectName("QuestionLabel")
        self.bYes = QtWidgets.QPushButton(self.centralwidget)
        self.bYes.setGeometry(QtCore.QRect(120, 40, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.bYes.setFont(font)
        self.bYes.setObjectName("bYes")
        self.bNo = QtWidgets.QPushButton(self.centralwidget)
        self.bNo.setGeometry(QtCore.QRect(200, 40, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.bNo.setFont(font)
        self.bNo.setObjectName("bNo")
        ConfirmationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ConfirmationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 395, 22))
        self.menubar.setObjectName("menubar")
        ConfirmationWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ConfirmationWindow)
        self.statusbar.setObjectName("statusbar")
        ConfirmationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ConfirmationWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfirmationWindow)

    def retranslateUi(self, ConfirmationWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfirmationWindow.setWindowTitle(_translate("ConfirmationWindow", "Confirmation Dialog"))
        self.QuestionLabel.setText(_translate("ConfirmationWindow", "Are you sure?"))
        self.bYes.setText(_translate("ConfirmationWindow", "Yes"))
        self.bNo.setText(_translate("ConfirmationWindow", "No"))
