# Form implementation generated from reading ui file 'DeleteAccFolderWindow.ui'
#
# Created by: PyQt6 UI code generator 6.0.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeleteAccFolderWindow(object):
    def setupUi(self, DeleteAccFolderWindow):
        DeleteAccFolderWindow.setObjectName("DeleteAccFolderWindow")
        DeleteAccFolderWindow.resize(342, 108)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        DeleteAccFolderWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(DeleteAccFolderWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FolderNameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.FolderNameInput.setGeometry(QtCore.QRect(10, 10, 321, 22))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.FolderNameInput.setFont(font)
        self.FolderNameInput.setObjectName("FolderNameInput")
        self.bDeleteAccFolder = QtWidgets.QPushButton(self.centralwidget)
        self.bDeleteAccFolder.setGeometry(QtCore.QRect(110, 40, 121, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        self.bDeleteAccFolder.setFont(font)
        self.bDeleteAccFolder.setObjectName("bDeleteAccFolder")
        DeleteAccFolderWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DeleteAccFolderWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 342, 22))
        self.menubar.setObjectName("menubar")
        DeleteAccFolderWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DeleteAccFolderWindow)
        self.statusbar.setObjectName("statusbar")
        DeleteAccFolderWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DeleteAccFolderWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteAccFolderWindow)

    def retranslateUi(self, DeleteAccFolderWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteAccFolderWindow.setWindowTitle(_translate("DeleteAccFolderWindow", "Delete Acc Folder"))
        self.bDeleteAccFolder.setText(_translate("DeleteAccFolderWindow", "Delete Acc Folder"))
