# Form implementation generated from reading ui file 'GenerateStrongPassWindow.ui'
#
# Created by: PyQt6 UI code generator 6.0.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GenerateStrongPassWindow(object):
    def setupUi(self, GenerateStrongPassWindow):
        GenerateStrongPassWindow.setObjectName("GenerateStrongPassWindow")
        GenerateStrongPassWindow.resize(534, 143)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        GenerateStrongPassWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(GenerateStrongPassWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NumberOfCharsInput = QtWidgets.QLineEdit(self.centralwidget)
        self.NumberOfCharsInput.setGeometry(QtCore.QRect(160, 10, 201, 22))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.NumberOfCharsInput.setFont(font)
        self.NumberOfCharsInput.setObjectName("NumberOfCharsInput")
        self.bGenerateStrongPass = QtWidgets.QPushButton(self.centralwidget)
        self.bGenerateStrongPass.setGeometry(QtCore.QRect(370, 10, 151, 24))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        self.bGenerateStrongPass.setFont(font)
        self.bGenerateStrongPass.setObjectName("bGenerateStrongPass")
        self.NumberOfCharsLabel = QtWidgets.QLabel(self.centralwidget)
        self.NumberOfCharsLabel.setGeometry(QtCore.QRect(10, 10, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        self.NumberOfCharsLabel.setFont(font)
        self.NumberOfCharsLabel.setObjectName("NumberOfCharsLabel")
        self.OutputLabel = QtWidgets.QLabel(self.centralwidget)
        self.OutputLabel.setGeometry(QtCore.QRect(240, 40, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        self.OutputLabel.setFont(font)
        self.OutputLabel.setObjectName("OutputLabel")
        self.OutputText = QtWidgets.QLineEdit(self.centralwidget)
        self.OutputText.setGeometry(QtCore.QRect(12, 70, 511, 22))
        self.OutputText.setReadOnly(True)
        self.OutputText.setObjectName("OutputText")
        GenerateStrongPassWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GenerateStrongPassWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 534, 22))
        self.menubar.setObjectName("menubar")
        GenerateStrongPassWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GenerateStrongPassWindow)
        self.statusbar.setObjectName("statusbar")
        GenerateStrongPassWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GenerateStrongPassWindow)
        QtCore.QMetaObject.connectSlotsByName(GenerateStrongPassWindow)

    def retranslateUi(self, GenerateStrongPassWindow):
        _translate = QtCore.QCoreApplication.translate
        GenerateStrongPassWindow.setWindowTitle(_translate("GenerateStrongPassWindow", "Generate Strong Password"))
        self.bGenerateStrongPass.setText(_translate("GenerateStrongPassWindow", "Generate Strong Pass"))
        self.NumberOfCharsLabel.setText(_translate("GenerateStrongPassWindow", "Number of Chars:"))
        self.OutputLabel.setText(_translate("GenerateStrongPassWindow", "Output:"))
