# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.0.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(492, 188)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        LoginWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("F:/Downloads/SSH-Keys.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        LoginWindow.setWindowIcon(icon)
        LoginWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bLogin = QtWidgets.QPushButton(self.centralwidget)
        self.bLogin.setGeometry(QtCore.QRect(10, 10, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.bLogin.setFont(font)
        self.bLogin.setObjectName("bLogin")
        self.bRegister = QtWidgets.QPushButton(self.centralwidget)
        self.bRegister.setGeometry(QtCore.QRect(170, 10, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.bRegister.setFont(font)
        self.bRegister.setObjectName("bRegister")
        self.bRemoveAccount = QtWidgets.QPushButton(self.centralwidget)
        self.bRemoveAccount.setGeometry(QtCore.QRect(330, 10, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.bRemoveAccount.setFont(font)
        self.bRemoveAccount.setObjectName("bRemoveAccount")
        self.bStyleManager = QtWidgets.QPushButton(self.centralwidget)
        self.bStyleManager.setGeometry(QtCore.QRect(170, 80, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.bStyleManager.setFont(font)
        self.bStyleManager.setObjectName("bStyleManager")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 22))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Login Window"))
        self.bLogin.setText(_translate("LoginWindow", "Login"))
        self.bLogin.setShortcut(_translate("LoginWindow", "1"))
        self.bRegister.setText(_translate("LoginWindow", "Register"))
        self.bRegister.setShortcut(_translate("LoginWindow", "2"))
        self.bRemoveAccount.setText(_translate("LoginWindow", "Remove\n"
"Account"))
        self.bRemoveAccount.setShortcut(_translate("LoginWindow", "3"))
        self.bStyleManager.setText(_translate("LoginWindow", "Style Manager"))
        self.bStyleManager.setShortcut(_translate("LoginWindow", "4"))
